In [3]:
import pandas as pd
import numpy as np
import seaborn as sns

C:\Users\DELL\anaconda3\lib\importlib\_bootstrap.py:219: RuntimeWarning: numpy.ufunc size changed, may indicate binary incompatibility. Expected 192 from C header, got 216 from PyObject
  return f(*args, **kwds)
C:\Users\DELL\anaconda3\lib\importlib\_bootstrap.py:219: RuntimeWarning: numpy.ufunc size changed, may indicate binary incompatibility. Expected 192 from C header, got 216 from PyObject
  return f(*args, **kwds)


In [4]:
#Reading the data
data = pd.read_csv("https://raw.githubusercontent.com/Mounika-Kajjam/Datasets/master/spam.csv",
                  encoding = 'latin-1')
data.head()

v1                                                 v2 Unnamed: 2  \
0   ham  Go until jurong point, crazy.. Available only ...        NaN   
1   ham                      Ok lar... Joking wif u oni...        NaN   
2  spam  Free entry in 2 a wkly comp to win FA Cup fina...        NaN   
3   ham  U dun say so early hor... U c already then say...        NaN   
4   ham  Nah I don't think he goes to usf, he lives aro...        NaN   

  Unnamed: 3 Unnamed: 4  
0        NaN        NaN  
1        NaN        NaN  
2        NaN        NaN  
3        NaN        NaN  
4        NaN        NaN

In [5]:
data.shape

(5572, 5)

In [6]:
data.drop(['Unnamed: 2', 'Unnamed: 3', 'Unnamed: 4'], axis = 1, inplace = True)
data.shape

(5572, 2)

In [7]:
#Split the data
#80% of the data will be in training data and 20% of the data will be in test data
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(data.v2, data.v1, test_size= 0.2)

C:\Users\DELL\anaconda3\lib\importlib\_bootstrap.py:219: RuntimeWarning: numpy.ufunc size changed, may indicate binary incompatibility. Expected 192 from C header, got 216 from PyObject
  return f(*args, **kwds)


In [8]:
print(X_train.shape)
print(X_test.shape)
print(y_train.shape)
print(y_test.shape)

(4457,)
(1115,)
(4457,)
(1115,)


In [9]:
#CountVertorizer
from sklearn.feature_extraction.text import CountVectorizer

#Creating an object for CountVertorizer
count_vect = CountVectorizer()

In [10]:
#Generate the word counts for the words in the documents 
word_count_vector = count_vect.fit(X_train)
word_count_vector

CountVectorizer(analyzer='word', binary=False, decode_error='strict',
                dtype=<class 'numpy.int64'>, encoding='utf-8', input='content',
                lowercase=True, max_df=1.0, max_features=None, min_df=1,
                ngram_range=(1, 1), preprocessor=None, stop_words=None,
                strip_accents=None, token_pattern='(?u)\\b\\w\\w+\\b',
                tokenizer=None, vocabulary=None)

In [11]:
word_count_vector.get_feature_names()

['00',
 '000',
 '000pes',
 '008704050406',
 '0089',
 '0121',
 '01223585236',
 '01223585334',
 '0125698789',
 '02',
 '0207',
 '02073162414',
 '02085076972',
 '021',
 '03',
 '04',
 '0430',
 '05',
 '050703',
 '0578',
 '06',
 '07',
 '07008009200',
 '07046744435',
 '07090201529',
 '07090298926',
 '07099833605',
 '07123456789',
 '0721072',
 '07732584351',
 '07734396839',
 '07742676969',
 '07753741225',
 '0776xxxxxxx',
 '07781482378',
 '07786200117',
 '077xxx',
 '078',
 '07801543489',
 '07808',
 '07808247860',
 '07815296484',
 '07821230901',
 '078498',
 '07880867867',
 '07946746291',
 '0796xxxxxx',
 '07973788240',
 '07xxxxxxxxx',
 '08',
 '0800',
 '08000407165',
 '08000776320',
 '08000839402',
 '08000930705',
 '08000938767',
 '08001950382',
 '08002888812',
 '08002986030',
 '08002986906',
 '08002988890',
 '08006344447',
 '0808',
 '08081263000',
 '08081560665',
 '0825',
 '0844',
 '08448350055',
 '08448714184',
 '0845',
 '08452810071',
 '08452810073',
 '08452810075over18',
 '0870',
 '08700469649'

In [12]:
doc_array = word_count_vector.transform(X_train)
doc_array

<4457x7721 sparse matrix of type '<class 'numpy.int64'>'
	with 59092 stored elements in Compressed Sparse Row format>

In [13]:
#Converting to an array
doc_array = word_count_vector.transform(X_train).toarray()
doc_array

array([[0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       ...,
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0]], dtype=int64)

In [14]:
#Converting array into dataframe
feature_matrix = pd.DataFrame(doc_array, columns = word_count_vector.get_feature_names())
feature_matrix

00  000  000pes  008704050406  0089  0121  01223585236  01223585334  \
0      0    0       0             0     0     0            0            0   
1      0    0       0             0     0     0            0            0   
2      0    0       0             0     0     0            0            0   
3      0    0       0             0     0     0            0            0   
4      0    0       0             0     0     0            0            0   
...   ..  ...     ...           ...   ...   ...          ...          ...   
4452   0    0       0             0     0     0            0            0   
4453   0    0       0             0     0     0            0            0   
4454   0    0       0             0     0     0            0            0   
4455   0    0       0             0     0     0            0            0   
4456   0    0       0             0     0     0            0            0   

      0125698789  02  ...  ìï  ó_  û_  û_thanks  ûªm  ûªt  ûï  ûïharry  ûò  \
0              0   0  ...   0   0   0         0    0    0   0        0   0   
1              0   0  ...   0   0   0         0    0    0   0        0   0   
2              0   0  ...   0   0   0         0    0    0   0        0   0   
3              0   0  ...   0   0   0         0    0    0   0        0   0   
4              0   0  ...   0   0   0         0    0    0   0        0   0   
...          ...  ..  ...  ..  ..  ..       ...  ...  ...  ..      ...  ..   
4452           0   0  ...   0   0   0         0    0    0   0        0   0   
4453           0   0  ...   0   0   0         0    0    0   0        0   0   
4454           0   0  ...   0   0   0         0    0    0   0        0   0   
4455           0   0  ...   0   0   0         0    0    0   0        0   0   
4456           0   0  ...   0   0   0         0    0    0   0        0   0   

      ûówell  
0          0  
1          0  
2          0  
3          0  
4          0  
...      ...  
4452       0  
4453       0  
4454       0  
4455       0  
4456       0  

[4457 rows x 7721 columns]

In [15]:
#pd.set_option('display.max_rows', None)

In [16]:
#TFIDF vectorizer
from sklearn.feature_extraction.text import TfidfVectorizer

#intialize and object for TFIDF vectorizer
tfidf = TfidfVectorizer()

In [19]:
# apply the tfidf to the data(X_train)
X_train_transformed = tfidf.fit_transform(X_train)
X_train_transformed

<4457x7721 sparse matrix of type '<class 'numpy.float64'>'
	with 59092 stored elements in Compressed Sparse Row format>

In [20]:
X_test_transformed = tfidf.transform(X_test)
X_test_transformed

<1115x7721 sparse matrix of type '<class 'numpy.float64'>'
	with 13796 stored elements in Compressed Sparse Row format>

In [21]:
#Feature Nmaes
tfidf.get_feature_names()

['00',
 '000',
 '000pes',
 '008704050406',
 '0089',
 '0121',
 '01223585236',
 '01223585334',
 '0125698789',
 '02',
 '0207',
 '02073162414',
 '02085076972',
 '021',
 '03',
 '04',
 '0430',
 '05',
 '050703',
 '0578',
 '06',
 '07',
 '07008009200',
 '07046744435',
 '07090201529',
 '07090298926',
 '07099833605',
 '07123456789',
 '0721072',
 '07732584351',
 '07734396839',
 '07742676969',
 '07753741225',
 '0776xxxxxxx',
 '07781482378',
 '07786200117',
 '077xxx',
 '078',
 '07801543489',
 '07808',
 '07808247860',
 '07815296484',
 '07821230901',
 '078498',
 '07880867867',
 '07946746291',
 '0796xxxxxx',
 '07973788240',
 '07xxxxxxxxx',
 '08',
 '0800',
 '08000407165',
 '08000776320',
 '08000839402',
 '08000930705',
 '08000938767',
 '08001950382',
 '08002888812',
 '08002986030',
 '08002986906',
 '08002988890',
 '08006344447',
 '0808',
 '08081263000',
 '08081560665',
 '0825',
 '0844',
 '08448350055',
 '08448714184',
 '0845',
 '08452810071',
 '08452810073',
 '08452810075over18',
 '0870',
 '08700469649'

In [22]:
#Position of the words in the sparse matrix
tfidf.vocabulary_

{'no': 4789,
 'shit': 6061,
 'but': 1572,
 'wasn': 7346,
 'that': 6780,
 'surprised': 6597,
 'so': 6244,
 'went': 7415,
 'and': 963,
 'spent': 6340,
 'the': 6785,
 'evening': 2664,
 'with': 7502,
 'french': 2999,
 'guy': 3276,
 'met': 4457,
 'in': 3638,
 'town': 6972,
 'here': 3407,
 'we': 7371,
 'fooled': 2937,
 'around': 1073,
 'bit': 1361,
 'didn': 2302,
 'let': 4084,
 'him': 3433,
 'fuck': 3031,
 'me': 4404,
 'ok': 4910,
 'lor': 4208,
 'im': 3610,
 'late': 4024,
 'tellmiss': 6725,
 'on': 4925,
 'my': 4664,
 'way': 7367,
 'cant': 1638,
 'pick': 5183,
 'phone': 5169,
 'right': 5760,
 'now': 4836,
 'pls': 5239,
 'send': 5978,
 'message': 4452,
 'are': 1053,
 'you': 7665,
 'staying': 6422,
 'got': 3202,
 'job': 3829,
 'wipro': 7492,
 'will': 7473,
 'get': 3122,
 'every': 2670,
 'thing': 6809,
 'life': 4099,
 'or': 4962,
 'years': 7638,
 'how': 3517,
 'abt': 764,
 'making': 4326,
 'some': 6256,
 'of': 4887,
 'pics': 5187,
 'bigger': 1342,
 'just': 3874,
 'buy': 1577,
 'pizza': 5209,
 'm

In [23]:
# Idf of the terms
tfidf.idf_

array([7.32301397, 6.2669613 , 8.70930833, ..., 8.70930833, 7.45654536,
       8.70930833])

In [24]:
# Apply the Naive Bayes Algorithm 

#Import BernoulliNB
from sklearn.naive_bayes import BernoulliNB

#Creating an object for BerNb
model_BerNB = BernoulliNB()

In [25]:
#Applying the algorithm to the data
#ObjectName.fit(Input, Output)

model_BerNB.fit(X_train_transformed, y_train)

BernoulliNB(alpha=1.0, binarize=0.0, class_prior=None, fit_prior=True)

In [26]:
#Prediction on test data
#Syntax: objectName.predict(InputValues)
y_test_pred = model_BerNB.predict(X_test_transformed)

In [27]:
#Compare the actual values(y_test) with predictes values(y_test_pred)
from sklearn.metrics import confusion_matrix, classification_report
confusion_matrix(y_test, y_test_pred)

array([[956,   0],
       [ 25, 134]], dtype=int64)

In [28]:
print(classification_report(y_test, y_test_pred))

              precision    recall  f1-score   support

         ham       0.97      1.00      0.99       956
        spam       1.00      0.84      0.91       159

    accuracy                           0.98      1115
   macro avg       0.99      0.92      0.95      1115
weighted avg       0.98      0.98      0.98      1115



In [30]:
#Test a singlr message--> Spam or Ham
new_message = pd.Series('Last few days for the to collect the free entry passes with 40% discount')

#Calcuate tfidf values for the new message
new_message_transformed = tfidf.transform(new_message)

In [31]:
#Predict the new message
model_BerNB.predict(new_message_transformed)

array(['ham'], dtype='<U4')

In [ ]:
#nltk--> text data (natural language tool kit)