In [4]:
from numpy import random
print(random.randint(1,100))#random integer in the given range
print(random.rand())#float number 0-1

49
0.31437811377060376


In [7]:
#creating an array with random integer values
print(random.randint(100,size=(3)))
print(random.randint(100,size=(3,4)))
print(random.randint(100,size=(3,4,2)))

[50 19 55]
[[72 64 60 60]
 [ 7 19  9  2]
 [54  1 37 82]]
[[[43 77]
  [78 47]
  [ 9  8]
  [61 70]]

 [[31 42]
  [77 71]
  [16 38]
  [49 62]]

 [[ 2 88]
  [14 98]
  [29 82]
  [19 92]]]


In [8]:
#creating n-dimensional array with random floating-point values
print(random.rand())
print(random.rand(3))
print(random.rand(2,3))

0.5317632077844041
[0.25202935 0.83287049 0.05351451]
[[0.92409227 0.59982025 0.42901416]
 [0.60528331 0.02705158 0.07622088]]


In [12]:
a=random.randint(100,size=(3,2)).ravel()
a

array([13, 33, 67, 20, 87, 11])

In [13]:
#single element will be selected
random.choice(a)

67

In [14]:
#for generating an array with the given shape and elements from the given list
random.choice([1,2,3,4,5],size=(3,4))

array([[3, 3, 1, 5],
       [2, 2, 3, 5],
       [4, 1, 2, 3]])

### pandas:
1. Data manipulation
2. Tabular,Unlabelled

### Creating a DataFrame
1. Using 2 dictionaries
2. Simple dictionary --> DataFrame

In [17]:
import pandas as pd
import numpy as np
dict1={'a':1,'b':2,'c':3,'d':4,'e':5}
dict2={'a':5,'b':6,'c':7,'d':8,'f':9}
data={"First":dict1,"Second":dict2}
df=pd.DataFrame(data,dtype=np.int32)
df #NaN --> not a number

First  Second
a    1.0     5.0
b    2.0     6.0
c    3.0     7.0
d    4.0     8.0
e    5.0     NaN
f    NaN     9.0

In [18]:
import pandas as pd
import numpy as np
dict1={'a':1,'b':2,'c':3,'d':4,'e':5}
dict2={'a':5,'b':6,'c':7,'d':8,'e':9}
data={"First":dict1,"Second":dict2}
df=pd.DataFrame(data,dtype=np.int32)
df

First  Second
a      1       5
b      2       6
c      3       7
d      4       8
e      5       9

In [24]:
#Simple dictionary --> DataFrame
d1={"name":["yasasvi","thati","charita"],"address":["hyd","adb","ap"]}
df1=pd.DataFrame(d1)
df1

name address
0  yasasvi     hyd
1    thati     adb
2  charita      ap

In [26]:
#using  Series
s1=pd.Series([1,2,3,4,5,6,7,8,9,10])
s2=pd.Series([12.23,23.34,45.3,45.5,67.4,67.78,34.45,23.34,67.4,23])
s3=pd.Series(['a','b','c','d','e','f','g','h','i','j'])
data={"column1":s1,"column2":s2,"column3":s3}
df3=pd.DataFrame(data)
df3

column1  column2 column3
0        1    12.23       a
1        2    23.34       b
2        3    45.30       c
3        4    45.50       d
4        5    67.40       e
5        6    67.78       f
6        7    34.45       g
7        8    23.34       h
8        9    67.40       i
9       10    23.00       j

### Selecting the data from the DataFrame:
1. loc -->row and column labels
2. iloc --> row and column index

In [27]:
df3["column2"]

0    12.23
1    23.34
2    45.30
3    45.50
4    67.40
5    67.78
6    34.45
7    23.34
8    67.40
9    23.00
Name: column2, dtype: float64

In [28]:
df3[["column2","column3"]]

column2 column3
0    12.23       a
1    23.34       b
2    45.30       c
3    45.50       d
4    67.40       e
5    67.78       f
6    34.45       g
7    23.34       h
8    67.40       i
9    23.00       j

In [30]:
#single column
df3.loc[:,"column1"]

0     1
1     2
2     3
3     4
4     5
5     6
6     7
7     8
8     9
9    10
Name: column1, dtype: int64

In [33]:
#extracting multiple column values
df3.loc[0:5,["column1","column2"]]

column1  column2
0        1    12.23
1        2    23.34
2        3    45.30
3        4    45.50
4        5    67.40
5        6    67.78

In [34]:
df3.iloc[:,0]

0     1
1     2
2     3
3     4
4     5
5     6
6     7
7     8
8     9
9    10
Name: column1, dtype: int64

In [35]:
df3.iloc[0:4,0:1]

column1
0        1
1        2
2        3
3        4

### Retrieving the information of DataFrame

In [36]:
df3.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 10 entries, 0 to 9
Data columns (total 3 columns):
 #   Column   Non-Null Count  Dtype  
---  ------   --------------  -----  
 0   column1  10 non-null     int64  
 1   column2  10 non-null     float64
 2   column3  10 non-null     object 
dtypes: float64(1), int64(1), object(1)
memory usage: 368.0+ bytes


In [37]:
df3.shape

(10, 3)

In [38]:
df3.columns

Index(['column1', 'column2', 'column3'], dtype='object')

In [39]:
df3.index

RangeIndex(start=0, stop=10, step=1)

### Viewing data from DataFrame:
1. head()
2. tail()
3. sample()


In [40]:
#First 5 rows
df3.head()

column1  column2 column3
0        1    12.23       a
1        2    23.34       b
2        3    45.30       c
3        4    45.50       d
4        5    67.40       e

In [42]:
df3.head(3)

column1  column2 column3
0        1    12.23       a
1        2    23.34       b
2        3    45.30       c

In [43]:
df3.tail()

column1  column2 column3
5        6    67.78       f
6        7    34.45       g
7        8    23.34       h
8        9    67.40       i
9       10    23.00       j

In [44]:
df3.tail(2)

column1  column2 column3
8        9     67.4       i
9       10     23.0       j

In [46]:
df3.sample(2)

column1  column2 column3
9       10    23.00       j
7        8    23.34       h

In [47]:
df3.sample()

column1  column2 column3
4        5     67.4       e

In [48]:
df3.describe()

column1    column2
count  10.00000  10.000000
mean    5.50000  40.974000
std     3.02765  20.997852
min     1.00000  12.230000
25%     3.25000  23.340000
50%     5.50000  39.875000
75%     7.75000  61.925000
max    10.00000  67.780000

In [50]:
#renaming the column headers
df3=df3.rename(columns={"column1":"First","column2":"Second","column3":"Third"})
df3
#df3.rename(columns={"column1":"First","column2":"Second","column3":"Third"}).inplace=True --> can also be used to rename col names permanently

First  Second Third
0      1   12.23     a
1      2   23.34     b
2      3   45.30     c
3      4   45.50     d
4      5   67.40     e
5      6   67.78     f
6      7   34.45     g
7      8   23.34     h
8      9   67.40     i
9     10   23.00     j