### Module:
1. Pre-defined modules
2. User-defined modules

In [2]:
import string
string.digits

'0123456789'

In [3]:
import string as s
s.digits

'0123456789'

In [5]:
from string import digits,punctuation
print(digits)
print(punctuation)

0123456789
!"#$%&'()*+,-./:;<=>?@[\]^_`{|}~


In [6]:
from string import *

In [26]:
list1=[1,2,3,4,5]
s=0
for i in list1:
    s+=i
print(sum)
#print(sum(list1))

15


### User-defined Modules:

In [14]:
import operations as o
o.wish("yasasvi")

good afternoon yasasvi


In [15]:
o.result

'True'

### Built-in functions:
1. math
2.

In [16]:
import math

In [19]:
math.factorial(5)

120

In [22]:
#using math module find out area of the circle
def area(radius):
    return math.pi*radius*radius
area(7)

153.93804002589985

In [23]:
def area(radius):
    return math.pi*math.pow(radius,2)
area(7)

153.93804002589985

In [2]:
import statistics as st
list1=list(range(1,21))
list1

[1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20]

In [3]:
print(st.mean(list1))
print(sum(list1)/len(list1))

10.5
10.5


In [4]:
print(st.median(list1))

10.5


In [9]:
list2=[1,2,3,4,3,3,4,2,2,2]
print(st.mode(list2))

2


In [10]:
st.stdev(list2)

0.9660917830792959

In [11]:
st.variance(list2)

0.9333333333333333

### random:
1. randint() --> randint(start,stop)
2. randrange() -->stop value is excluded
3. random() -->0-1
4. choice()

In [16]:
import random
print(random.randint(1,10))
print(random.randrange(1,10))
print(random.random())

6
3
0.5240999169800608


In [20]:
list1=[1,2,3,4,5,6,7,8]
print(random.choice(list1))
print(random.choices(list1,k=3))

1
[6, 7, 2]


### os:
1. remove() --> removing
2. rename() -->renaming
3. mkdir()  --> make a directory
4. getcwd() --> get current working directory
5. listdir() -->gives you list of things
6. chdir()   --> change directory
7. rmdir()   -->removing the directory

In [21]:
import os
os.mkdir("sample")

In [22]:
os.getcwd()

'C:\\Users\\DELL\\Desktop\\Internship\\Data Science'

In [23]:
os.listdir()

['.git',
 '.ipynb_checkpoints',
 'Assignment -1.ipynb',
 'Assignment -2(28-05-2020).ipynb',
 'Assignment 3(29-02-2020).ipynb',
 'Assignment 5(1-06-2020).ipynb',
 'Assignment 6(2-06-2020).ipynb',
 'Day 2(27-05-2020).ipynb',
 'Day 3(28-05-2020).ipynb',
 'Day 4(29-05-2020).ipynb',
 'Day 5(30-05-2020).ipynb',
 'Day 6(1-06-2020).ipynb',
 'Day 7(2-06-2020).ipynb',
 'Day 8(3-06-2020).ipynb',
 'New',
 'operations.py',
 'python class',
 'sample',
 'sample.txt',
 '__pycache__']

In [29]:
os.chdir('C:\\Users\\DELL\\Desktop\\Internship\\Data Science')

In [30]:
os.getcwd()

'C:\\Users\\DELL\\Desktop\\Internship\\Data Science'

In [31]:
os.rmdir("sample")

### Numpy Packages:
1. operations related to numerics
2. Computational operations

In [2]:
import numpy as np
list1=[1,2,3,4,5]
arr1=np.array(list1)
print(arr1)
type(arr1)

[1 2 3 4 5]


numpy.ndarray

In [3]:
list2=list(range(1,11))
list2

[1, 2, 3, 4, 5, 6, 7, 8, 9, 10]

In [6]:
arr2=np.arange(1,11)
arr2

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

### Difference between python list and numpy array
1. Less memory compare to python list
2. Fast
3. convenient than python list

In [9]:
import sys
size=1000
list1= list(range(size))
print(sys.getsizeof(list1[0])*size)
arr1=np.arange(1000)
print(arr1.itemsize*arr1.size)

24000
4000


In [41]:
import time
size=20000
list1=list(range(size))
list2=list(range(size))
start=time.time()
result=[x+y for x,y in zip(l1,l2)]
print("time took for python list:",time.time()-start)
arr1=np.arange(size)
arr2=np.arange(size)
start=time.time()
result=arr1+arr2
print("time took for numpy array:",time.time()-start)

time took for python list: 0.0009999275207519531
time took for numpy array: 0.003000497817993164


In [18]:
l1=[1,2,3,4,5]
l2=[10,11,12,23,14]
#result=[11,13,15,27,19]
result=[x+y for x,y in zip(l1,l2)]
result

[11, 13, 15, 27, 19]

In [15]:
a1=np.array(l1)
a2=np.array(l2)
a1+a2

array([11, 13, 15, 27, 19])